#if UNITY_EDITOR
using ShadowTheater.UI;using UnityEditor;using UnityEditor.Events;using UnityEngine;using UnityEngine.UI;
namespace ShadowTheater.EditorTools
{
 public static class QuestLogPrefabGenerator
 {
  const string Path="Assets/Prefabs/UI/QuestLogCanvas.prefab";
  [MenuItem("Tools/Shadow Theater/Generate Quest Log UI")]
  public static void Generate(){Ensure("Assets","Prefabs");Ensure("Assets/Prefabs","UI");var canvasGo=new GameObject("QuestLogCanvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster),typeof(QuestLogController));var c=canvasGo.GetComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;c.sortingOrder=58;var sc=canvasGo.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1080,1920);sc.matchWidthOrHeight=.5f;var root=Rect("Root",canvasGo.transform,Vector2.zero,Vector2.one);root.gameObject.AddComponent<Image>().color=new Color(.012f,.008f,.028f,.99f);Text("Header",root,new Vector2(.05f,.925f),new Vector2(.55f,.985f),44,"기억의 여정",TextAnchor.MiddleLeft);var count=Text("Count",root,new Vector2(.52f,.93f),new Vector2(.83f,.98f),21,"진행 0 · 완료 0",TextAnchor.MiddleRight);var close=Btn("Close",root,new Vector2(.86f,.93f),new Vector2(.96f,.98f),"×");var active=Btn("Active",root,new Vector2(.05f,.865f),new Vector2(.255f,.92f),"진행 중");var completed=Btn("Completed",root,new Vector2(.27f,.865f),new Vector2(.475f,.92f),"완료 기록");var list=Scroll("List",root,new Vector2(.05f,.08f),new Vector2(.475f,.85f),out var content);var template=Entry(content);template.gameObject.SetActive(false);var empty=Text("Empty",list.transform,new Vector2(.08f,.42f),new Vector2(.92f,.58f),22,"표시할 기록이 없습니다",TextAnchor.MiddleCenter);var detail=Rect("Detail",root,new Vector2(.51f,.08f),new Vector2(.95f,.85f));detail.gameObject.AddComponent<Image>().color=new Color(.035f,.025f,.07f);var title=Text("Title",detail,new Vector2(.06f,.84f),new Vector2(.94f,.96f),32,"기록을 선택하세요",TextAnchor.MiddleLeft);var summary=Text("Summary",detail,new Vector2(.06f,.64f),new Vector2(.94f,.84f),20,"",TextAnchor.UpperLeft);var objectives=Text("Objectives",detail,new Vector2(.06f,.26f),new Vector2(.94f,.64f),21,"",TextAnchor.UpperLeft);var reward=Text("Reward",detail,new Vector2(.06f,.08f),new Vector2(.94f,.23f),20,"",TextAnchor.UpperLeft);reward.color=new Color(1f,.79f,.37f);var ctrl=canvasGo.GetComponent<QuestLogController>();var so=new SerializedObject(ctrl);Set(so,"root",root.gameObject);Set(so,"contentRoot",content);Set(so,"entryTemplate",template);Set(so,"countText",count);Set(so,"titleText",title);Set(so,"summaryText",summary);Set(so,"objectivesText",objectives);Set(so,"rewardText",reward);Set(so,"emptyText",empty);Set(so,"activeFilterButton",active);Set(so,"completedFilterButton",completed);so.ApplyModifiedPropertiesWithoutUndo();UnityEventTools.AddPersistentListener(close.onClick,ctrl.Close);UnityEventTools.AddPersistentListener(active.onClick,ctrl.ShowActive);UnityEventTools.AddPersistentListener(completed.onClick,ctrl.ShowCompleted);root.gameObject.SetActive(false);PrefabUtility.SaveAsPrefabAsset(canvasGo,Path);Object.DestroyImmediate(canvasGo);AssetDatabase.SaveAssets();AssetDatabase.Refresh();Debug.Log("[Shadow Theater] 퀘스트 기록장 UI 생성 완료");}
  static QuestLogEntryView Entry(Transform p){var r=Rect("EntryTemplate",p,Vector2.zero,Vector2.one);r.gameObject.AddComponent<LayoutElement>().preferredHeight=110;var i=r.gameObject.AddComponent<Image>();i.color=new Color(.07f,.05f,.12f);var b=r.gameObject.AddComponent<Button>();b.targetGraphic=i;var state=Text("State",r,new Vector2(.03f,.12f),new Vector2(.13f,.88f),25,"▶",TextAnchor.MiddleCenter);var title=Text("Title",r,new Vector2(.15f,.45f),new Vector2(.78f,.91f),23,"퀘스트",TextAnchor.MiddleLeft);var progress=Text("Progress",r,new Vector2(.78f,.14f),new Vector2(.96f,.88f),19,"0/0",TextAnchor.MiddleRight);var view=r.gameObject.AddComponent<QuestLogEntryView>();var so=new SerializedObject(view);Set(so,"button",b);Set(so,"stateText",state);Set(so,"titleText",title);Set(so,"progressText",progress);so.ApplyModifiedPropertiesWithoutUndo();return view;}
  static ScrollRect Scroll(string n,Transform p,Vector2 min,Vector2 max,out RectTransform content){var r=Rect(n,p,min,max);r.gameObject.AddComponent<Image>().color=new Color(.028f,.02f,.055f);var v=Rect("Viewport",r,Vector2.zero,Vector2.one);v.gameObject.AddComponent<Image>().color=new Color(1,1,1,.01f);v.gameObject.AddComponent<Mask>().showMaskGraphic=false;content=Rect("Content",v,new Vector2(0,1),Vector2.one);content.pivot=new Vector2(.5f,1);var l=content.gameObject.AddComponent<VerticalLayoutGroup>();l.padding=new RectOffset(8,8,8,8);l.spacing=7;l.childControlHeight=true;l.childForceExpandHeight=false;content.gameObject.AddComponent<ContentSizeFitter>().verticalFit=ContentSizeFitter.FitMode.PreferredSize;var s=r.gameObject.AddComponent<ScrollRect>();s.viewport=v;s.content=content;s.horizontal=false;return s;}
  static Button Btn(string n,Transform p,Vector2 min,Vector2 max,string label){var r=Rect(n,p,min,max);var i=r.gameObject.AddComponent<Image>();i.color=new Color(.14f,.09f,.25f);var b=r.gameObject.AddComponent<Button>();b.targetGraphic=i;Text("Label",r,Vector2.zero,Vector2.one,22,label,TextAnchor.MiddleCenter);return b;}static Text Text(string n,Transform p,Vector2 min,Vector2 max,int size,string value,TextAnchor a){var r=Rect(n,p,min,max);var t=r.gameObject.AddComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.fontSize=size;t.text=value;t.alignment=a;t.color=new Color(.96f,.93f,1);t.raycastTarget=false;t.horizontalOverflow=HorizontalWrapMode.Wrap;return t;}static RectTransform Rect(string n,Transform p,Vector2 min,Vector2 max){var g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);var r=(RectTransform)g.transform;r.anchorMin=min;r.anchorMax=max;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;return r;}static void Set(SerializedObject s,string n,Object v)=>s.FindProperty(n).objectReferenceValue=v;static void Ensure(string p,string n){if(!AssetDatabase.IsValidFolder(p+"/"+n))AssetDatabase.CreateFolder(p,n);}
 }
}
#endif
